# Liste verticale des candidats
Vertical Candidate List=True
# Utiliser la molette de la souris pour aller à la page précédente ou suivante
WheelForPaging=True
# Police
Font="Sans Serif 13"
# Police du menu
MenuFont="Sans 13"
# Police du bac
TrayFont="Sans Bold 13"
# Couleur du contour de l'étiquette du plateau
TrayOutlineColor=#000000
# Couleur du texte de l'étiquette du plateau
TrayTextColor=#ffffff
# Préférer l'icône de texte
PreferTextIcon=False
# Afficher le nom de la mise en page dans l'icône
ShowLayoutNameInIcon=True
# Utiliser la langue de la méthode de saisie pour afficher le texte
UseInputMethodLanguageToDisplayText=True
# Thème
Theme=catppuccin-macchiato
# Dark Theme
DarkTheme=catppuccin-macchiato
# Follow system light/dark color scheme
UseDarkTheme=False
# Follow system accent color if it is supported by theme and desktop
UseAccentColor=True
# Use Per Screen DPI on X11
PerScreenDPI=False
# Force font DPI on Wayland
ForceWaylandDPI=0
# Enable fractional scale under Wayland
EnableFractionalScale=True

