color0 #10131c
color1 #ffb4ab
color2 #58d6f7
color3 #86d1e9
color4 #b1c5ff
color5 #58d6f7
color6 #86d1e9
color7 #e0e2ef
color8 #8a90a5
color9 #ffb4ab
color10 #58d6f7
color11 #86d1e9
color12 #b1c5ff
color13 #58d6f7
color14 #86d1e9
color15 #e0e2ef

cursor                #e0e2ef
cursor_text_color     #10131c
background            #10131c
foreground            #e0e2ef
selection_foreground  #c0c6dc
selection_background  #404659
active_border_color   #58d6f7
inactive_border_color #404659
url_color             #58d6f7

active_tab_foreground   #003641
active_tab_background   #58d6f7
inactive_tab_foreground #c0c6dc
inactive_tab_background #404659
cursor_trail_color      #c0c6dc
