$primary_paletteKeyColor = 0bb8ba
$secondary_paletteKeyColor = 268384
$tertiary_paletteKeyColor = 497ba6
$neutral_paletteKeyColor = 707881
$neutral_variant_paletteKeyColor = 6a7989
$background = 0d141b
$onBackground = dce3ee
$surface = 0d141b
$surfaceDim = 0d141b
$surfaceBright = 323a42
$surfaceContainerLowest = 080f16
$surfaceContainerLow = 151c24
$surfaceContainer = 192028
$surfaceContainerHigh = 232b32
$surfaceContainerHighest = 2e353e
$onSurface = dce3ee
$surfaceVariant = 3a4857
$onSurfaceVariant = b9c8da
$inverseSurface = dce3ee
$inverseOnSurface = 2a3139
$outline = 8392a3
$outlineVariant = 3a4857
$shadow = 000000
$scrim = 000000
$surfaceTint = 4cdadb
$primary = 4cdadb
$onPrimary = 003737
$primaryContainer = 004f50
$onPrimaryContainer = 6ff6f8
$inversePrimary = 00696a
$secondary = 80d4d5
$onSecondary = 003737
$secondaryContainer = 006f70
$onSecondaryContainer = 9cf1f1
$tertiary = 9acbfa
$onTertiary = 003353
$tertiaryContainer = 6495c1
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = 6ff6f8
$primaryFixedDim = 4cdadb
$onPrimaryFixed = 002020
$onPrimaryFixedVariant = 004f50
$secondaryFixed = 9cf1f1
$secondaryFixedDim = 80d4d5
$onSecondaryFixed = 002020
$onSecondaryFixedVariant = 004f50
$tertiaryFixed = cee5ff
$tertiaryFixedDim = 9acbfa
$onTertiaryFixed = 001d32
$onTertiaryFixedVariant = 0c4a73
$term0 = 343434
$term1 = 769e00
$term2 = 50e2c7
$term3 = 7bfcd5
$term4 = 75b5b6
$term5 = 7aaee9
$term6 = 82d8ce
$term7 = ccdcd4
$term8 = 9aa59f
$term9 = 85b900
$term10 = 35f7d8
$term11 = ccffec
$term12 = a3c8c5
$term13 = a2c0f7
$term14 = 89ecdf
$term15 = ffffff
$rosewater = f1f3e5
$flamingo = dfe0f5
$pink = bae2ff
$mauve = 63ceec
$red = 8ab5ff
$maroon = abbef0
$peach = a9daac
$yellow = d2faeb
$green = 8cf1e5
$teal = 9eedeb
$sky = 93e9ed
$sapphire = 71d6df
$blue = 59ccde
$lavender = 87d9eb
$klink = 0095a2
$klinkSelection = 0095a2
$kvisited = 008caa
$kvisitedSelection = 008cab
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = 34c359
$kneutralSelection = 34c359
$kpositive = 00bdb1
$kpositiveSelection = 00bdb2
$text = dce3ee
$subtext1 = b9c8da
$subtext0 = 8392a3
$overlay2 = 727f8f
$overlay1 = 606c7a
$overlay0 = 4f5a67
$surface2 = 3f4954
$surface1 = 2f3842
$surface0 = 1e262e
$base = 0d141b
$mantle = 0d141b
$crust = 0c131a
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
