input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = yes
    }
    sensitivity = 0
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    layout = dwindle
    allow_tearing = false
}

decoration {
    rounding = 10
    blur {
        enabled = true
        size = 3
        passes = 1
    }
}

animations {
    enabled = yes
    bezier = twentieth, 0.05, 0.9, 0.1, 1.0
    animation = windowsIn, 1, 8, twentieth, slidefade 50%
    animation = windowsOut, 1, 7, default, slidefade 100%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 5, twentieth
    animation = workspaces, 1, 6, twentieth, slidefade 3%
}

dwindle {
    preserve_split = yes
}

gestures {
    workspace_swipe = on
    workspace_swipe_fingers = 3
    workspace_swipe_min_speed_to_force = 50
    workspace_swipe_distance = 100
    workspace_swipe_cancel_ratio = 0.5
}

misc {
    force_default_wallpaper = 0
}

debug {
    disable_scale_checks = true
}

windowrulev2 = suppressevent maximize, class:.*
windowrule = float,title:^(Picture-in-Picture)$
