monitor=,preferred,auto,2

exec-once = caelestia shell -d
exec-once = nm-applet
exec-once = blueman-applet
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = easyeffects --gapplication-service

source = ~/.config/hypr/env.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/general.conf
source = ~/.config/hypr/colors.conf

