monitor=,highres,auto,1.5

exec-once = waybar
exec-once = hyprpaper
exec-once = nm-applet
exec-once = blueman-applet
exec-once = fcitx5
exec-once = swaync
exec-once = swayosd-server
exec-once = hypridle
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

source = ~/.config/hypr/env.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/general.conf

