format = '''
$os $shell $username $hostname $directory
$character
'''
right_format = "$battery"

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "
style = "yellow bold"
format = "[ $path]($style)"

[docker_context]
symbol = " "

[dotnet]
symbol = ""
style = "blue bold"
format = "via [$symbol $version]($style)"

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "
style = "blue bold"
format = "branch [$symbol$branch]($style) "

[git_status] 
format = "[$all_status$ahead_behind]($style) "
style = "red bold"

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = ""
style = "red bold"
format = " via [$symbol $version]($style)" 

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "

[meson]
symbol = "喝 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os]
format = "[$symbol Arch Linux](bold cyan)"
disabled = false

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[package]
symbol = " "

[python]
symbol = " "
style = "cyan bold"
format = "via [$symbol$version]($style) "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = " "

[shell]
zsh_indicator = "zsh"
fish_indicator = "fish"
nu_indicator = "nushell"
format = "[󰘳 $indicator](cyan bold)"
disabled = false

[scala]
symbol = " "

[spack]
symbol = "🅢 "

[username]
style_user = "blue bold"
style_root = "red bold"
format = "[ $user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
style = "purple bold"
format = "[ $hostname]($style)"

