# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=#0f1417

# Main text color
theme[main_fg]=#dfe3e7

# Title color for boxes
theme[title]=#dfe3e7

# Highlight color for keyboard shortcuts
theme[hi_fg]=#91cef5

# Background color of selected item in processes box
theme[selected_bg]=#1c2024

# Foreground color of selected item in processes box
theme[selected_fg]=#91cef5

# Color of inactive/disabled text
theme[inactive_fg]=#8b9298

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]=#ccc1e9

# Background color of the percentage meters
theme[meter_bg]=#8b9298

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]=#ccc1e9

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#8ec5ff
theme[mem_box]=#a7eaff
theme[net_box]=#abbef0
theme[proc_box]=#79c4fb

# Box divider line and small boxes line color
theme[div_line]=#41484d

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#a7eaff
theme[temp_mid]=#d0f9f4
theme[temp_end]=#8ab5ff

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#b4e7ff
theme[cpu_mid]=#85d0fc
theme[cpu_end]=#9fd2ff

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#8ec5ff
theme[free_mid]=#9fd2ff
theme[free_end]=#79c4fb

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#85d0fc
theme[cached_mid]=#79c4fb
theme[cached_end]=#9fd2ff

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#e0c2f9
theme[available_mid]=#abbef0
theme[available_end]=#8ab5ff

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#a7eaff
theme[used_mid]=#b4e7ff
theme[used_end]=#afe2ff

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#e0c2f9
theme[download_mid]=#abbef0
theme[download_end]=#8ab5ff

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#a7eaff
theme[upload_mid]=#b4e7ff
theme[upload_end]=#afe2ff

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#85d0fc
theme[process_mid]=#9fd2ff
theme[process_end]=#8ec5ff
