exec = cp -L --no-preserve=mode --update=none ~/.config/hypr/scheme/default.conf ~/.config/hypr/scheme/current.conf
source = ~/.config/hypr/scheme/current.conf

general {
    col.active_border = rgb($primaryFixedDim)
    col.inactive_border = rgb($neutral_paletteKeyColor)
}

group {
    groupbar {
        text_color = rgb($onPrimary)
        col.active = rgba($primaryd4)
        col.inactive = rgba($outlined4)
        col.locked_active = rgba($primaryd4)
        col.locked_inactive = rgba($secondaryd4)
    }
}

misc {
	background_color = rgb($surfaceVariant)
}
